qa prompt template and example
promptslab/PromptifyJs pull request #18
Opened 2023-03-11 01:56 UTC by Devorein

Implementation of QA prompt template along with example mentioned in #4

2023-03-11 12:21 UTC, arionrefat commented
There is no sample[] in qaData
![image](https://user-images.githubusercontent.com/37513070/224484166-6db56954-020c-4541-9a43-f7f65453337c.png)

2023-03-16 15:18 UTC, rk-teche requested changes

2023-03-16 15:18 UTC, rk-teche commented on examples/qaExample.js
> +const firstExample = examples.slice(0, 3);
I guess you need to create `qa.json` inside the example data then import it here

2023-03-23 03:42 UTC, rk-teche approved these changes

2023-03-23 03:42 UTC, merged